apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.micro-service.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-server
  name: zipkin-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.micro-service.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: zipkin-server
    spec:
      containers:
      - env:
        - name: RABBIT_URI
          value: amqp://guest:guest@rabbitmq:5672
        - name: STORAGE_TYPE
          value: mem
        image: openzipkin/zipkin
        name: zipkin
        ports:
        - containerPort: 9411
        resources: {}
      restartPolicy: Always
status: {}
